export enum ParticipantActionTypes {
  PARTICIPANT_FETCH_REQUESTED = "PARTICIPANT_FETCH_REQUESTED",
  PARTICIPANT_FETCH_SUCCESSFUL = "PARTICIPANT_FETCH_SUCCESSFUL",
  PARTICIPANT_FETCH_FAILED = "PARTICIPANT_FETCH_FAILED",
}
