export enum TeamActionTypes {
  TEAM_ID_SET = "TEAM_ID_SET",
  TEAM_FETCH_REQUESTED = "TEAM_FETCH_REQUESTED",
  TEAM_FETCH_SUCCESSFUL = "TEAM_FETCH_SUCCESSFUL",
  TEAM_FETCH_FAILED = "TEAM_FETCH_FAILED",
}
